# Please refer to ./readme.md for how to build single pull request

name: PR-1576

on:
  workflow_dispatch:

env:
  ## The pull request number of the Tracking pull request to merge the release branch to main
  PR_NUMBER: 1576
  VERSION: 1.47.0
  GIT_URL: https://github.com/bcgov/zeva.git 
  TOOLS_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-tools
  DEV_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:

  database:

    name: Start Database
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:

      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: refs/pull/${{ env.PR_NUMBER }}/head

      - name: Log in to Openshift
        uses: redhat-actions/oc-login@v1.2
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ${{ env.TOOLS_NAMESPACE }}    

      - name: Setup Database
        shell: bash {0}
        run: |
          cd charts/zeva-spilo
          helm status -n ${{ env.DEV_NAMESPACE }} zeva-spilo-dev-${{ env.PR_NUMBER }}
          if [ $? -eq 0 ]; then
            echo "zeva-spilo-dev-${{ env.PR_NUMBER }} exists already"
          else
            echo "Installing zeva-spilo-dev-${{ env.PR_NUMBER }}"
            helm install -n ${{ env.DEV_NAMESPACE }} -f ./values-dev-pr.yaml --wait zeva-spilo-dev-${{ env.PR_NUMBER }} .
            oc -n ${{ env.DEV_NAMESPACE }} wait --for=condition=Ready pod/zeva-spilo-dev-${{ env.PR_NUMBER }}-0
            oc -n ${{ env.DEV_NAMESPACE }} exec zeva-spilo-dev-${{ env.PR_NUMBER }}-0 psql -c "create CREATE USER ${{ secrets.ZEVA_DEV_USERNAME }} WITH PASSWORD '${{ secrets.ZEVA_DEV_PASSWORD }}'"
            oc -n ${{ env.DEV_NAMESPACE }} exec zeva-spilo-dev-${{ env.PR_NUMBER }}-0 psql -c "create database zeva owner ${{ secrets.ZEVA_DEV_USERNAME }} ENCODING 'UTF8' LC_COLLATE = 'en_US.UTF-8' LC_CTYPE = 'en_US.UTF-8'"

          fi


