# Please refer to ./readme.md for how to build single pull request

# Update this workflow name per pull request
name: Build PR on Dev

on:
  pull_request:
    types: [opened, edited, reopened]
    branches:
          - 'release-*'
  
jobs:
  show-vars:
    name: Show vars value
    runs-on: ubuntu-latest
    timeout-minutes: 20
 
    steps:

      - name: show all vars
        shell: bash {0}
        run: |
          echo "showing var secrets.OPENSHIFT_SERVER"
          echo "${{ secrets.OPENSHIFT_SERVER }}"

  call-pr-build:
    if: endsWith( github.event.pull_request.title, 'build-on-dev' )
    uses: ./.github/workflows/pr-build-template.yaml
    with:
      # Update pr-number per pull request
      pr-number: ${{ github.event.pull_request.number }}
      # Update pr-number per release
      version: ${{ github.event.pull_request.base.ref }}
    secrets:
      tools-namespace: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-tools
      dev-namespace: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-dev
      zeva-dev-username: ${{ secrets.ZEVA_DEV_USERNAME }}
      zeva-dev-password: ${{ secrets.ZEVA_DEV_PASSWORD }}
      openshift-server: ${{ secrets.OPENSHIFT_SERVER }}
      openshift-token: ${{ secrets.OPENSHIFT_TOKEN }}
