name: Label PR

on:
  pull_request:
    types: edited
    branches:
          - 'release-*'

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: testLabelPR

